### ISSUE TITLE
Sending 99% Error

### ISSUE THREAD

**Issue by wuscier** [mustakimali/JustA.ML#10]
when sending progress reaches 99%,  it prompted an error, Unexpected Error
404: 
![404error](https://user-images.githubusercontent.com/9278415/46660381-7d038000-cbe9-11e8-8d1a-0123e1db018b.png)

**Comment by mustakimali** [comment]
Did you retry with the same file? if yes, were you able to sent it? How large was this file?

I can only think of few scenarios
* An update was being deployed right at that moment (time of this post 10:34 BST yesterday makes me think this) OR Your internet dropped for a moment - either case as soon as you got disconnected - the app should delete all uploaded files.
* Or the anti virus flagged this file and removed this - I can check the log and find out more.

**Comment by mustakimali** [comment]
Closing this until I find a reliable way of reproducing this.
