### ISSUE TITLE
Waiting for secure connection - Can't share

### ISSUE THREAD

**Issue by jones1618** [mustakimali/JustA.ML#47]
I've enjoyed using Justa.ml for a couple of years now but suddenly it doesn't work any longer.
When trying to connect w/ my Android phone I see a "Establishing encrypted connection..." message but can't receive text.
### Note I just found that I can Start on Android and then Connect on PC, just not the other way around ###
Steps:

1. Click [Start] on Justa.ml on PC
2. Click [Connect] on Justa.ml on Android phone
3. Enter PIN on Android
4. Justa.ml shows "Establishing encrypted connection..." and "greys out" the screen on Android
5. Enter text on PC and click [Send]
6. New item appears on Android but says "Encrypted" and is greyed-out and not clickable

BTW: Grey area on Android covers entire Justa.ml web page but if you scroll, bottom of page is uncovered/not-grey.

All of this has worked well many times in the past but makes Just.ml unusable for me now.
### Note: I just tried starting on my Android and connecting from my PC and it works just fine. So, it only fails going the other way. That's just always how I've used Justa.ml. ###

Thanks for your very useful tool.
Regards,
   Stephen Jones
   Chicagoland, USA
   srjones1618@gmail.com

**Comment by mustakimali** [comment]
Thank you for reporting this. I had to find a few android phones to understand if it affects just a specific browser and was able to replicate this issue once as my Pixel phone (firefox and chrome) works. What phone and browser were you using? until I can reliably reproduce this, I will keep this issue open.

**Comment by jones1618** [comment]
The phone is an LG K30 running Android 8.1.0 and Chrome 79.034.
However, I just tried to reproduce it and couldn't (even though I reproduced it multiple times before submitting the bug). Go figure. Maybe a Chrome or Android update fixed it.
Thanks for looking into it. I'll close the issue.
