### ISSUE TITLE
"Fork me on Github" - banner makes "Did you find it useful" - dialog un-closable

### ISSUE THREAD

**Issue by DanielGilbert** [mustakimali/JustA.ML#49]
First of all, I really like just-an-email for what it is! And the new QR code featues is just awesome!

With this being said, I've a small ux issue when I'm on mobile - I'm using an iPhone X, and after a successful session, when I head back to the main page, I get the "Did you find it useful?" - dialog, which I cannot close, because the "x" is behind the transparent part of the "Fork me on Github" - image:

![image](https://user-images.githubusercontent.com/3011428/80914315-26b9dd00-8d4b-11ea-976b-2aff7735bb74.png)

You can recreate that also on desktop by just resizing the browser window so that it looks like on the image. Looks like the resolution of the iPhone is big enough to not trigger the full "hide that banner" logic.

**Comment by mustakimali** [comment]
Thanks for reporting this. ~I will indeed fix this soon.~ this is fixed now.
You an also tap anywhere in the grey area to dismiss this dialogue.

**Comment by DanielGilbert** [comment]
Thanks a lot for the fast fix! Of course, it didn't cross my mind to "tap to dismiss". :D
